version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet

  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet:
    driver: bridge
